### PR TITLE
Add local tests to project

### LINKED ISSUE #47: Add local tests to project
Study a way to automate testing.

### PR DESCRIPTION
**Pull request by Irineu333**
### Description

The implementation of tests is crucial to prevent regressions and accelerate development. This pull request represents a significant step towards full test coverage in Speak Touch.

Given that the SpeakTouch code intensely interacts with the Android framework APIs, local tests isolated from the Android framework are not viable. One option would be to simulate these structures with Mockito or Mockk. However, although valid, this approach requires the developer to code the simulated structures, which will most likely not reflect the actual behavior, but rather the developer's expectations. Therefore, I opted to use [Robolectric](https://robolectric.org/) to simulate the Android framework locally. This approach seems more effective and aligned with the application's real behavior. My experience with Robolectric was surprisingly positive, especially due to the ease of creating tests with it

### Improvements
- Added local tests for `Type`

### CODE REVIEW

**Review by PatrykMis — APPROVED** [review]
Great work! I've performed some cleanup regarding example tests and example instrumented tests, noticing that you removed the runners dependency. Additionally, I've updated the dependencies to avoid creating unnecessary pull requests, as everything will be reflected in the commit history.

**Comment by Irineu333** [comment]
@coderabbitai review

**Comment by Irineu333** [comment]
@PatrykMis I'm testing [CodeRabbit](https://coderabbit.ai/) on the project, do you like it? It's a free AI code review tool for open source projects.

**Comment by PatrykMis** [comment]
@Irineu333 it's a great tool which, as I see, summarizes changes made in pull requests, it is also capable to see them in context of linked issues.

And what about integrating [SonarCloud](https://github.com/apps/sonarcloud)?

**Comment by Irineu333** [comment]
@PatrykMis I don't know.. Can you introduce me to them?

**Comment by Irineu333** [comment]
I was a bit disappointed with the **CodeRabbit**. I thought it could point out potential problems in the code like a reviewer, but the comments are very generic (see #128). In this PR, it just summarized the changes.

Regarding **SonarCloud**, I will study it.

**Pull request merged**
